import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createDatabase, migrationUrl, save } from './fixtures/idea-images-db.mjs';
// Executes the real migration and RPC in an isolated in-memory Postgres.
// storage.objects below is a fixture, NOT the production Storage service.
const db = await createDatabase();
let checks = 0;
const ok = (name, condition) => { assert(condition,name); checks++; console.log(`PASS ${name}`); };
const url = n => `https://project.supabase.co/storage/v1/object/public/idea-images/ideas/${n}.png`;
const values = { title:'画像テスト',status:'アイデア',note:'メモ',tags:'テスト' };
ok('new attachment table has RLS enabled',(await db.query("select relrowsecurity from pg_class where oid='public.idea_images'::regclass")).rows[0].relrowsecurity);
ok('save RPC uses invoker rights and a fixed search path',(await db.query("select not prosecdef and proconfig @> array['search_path=\"\"'] as safe from pg_proc where proname='save_idea_with_images'")).rows[0].safe);
const legacy = (await db.query('insert into public.ideas(title,image_url) values($1,$2) returning *',['旧画像',url('legacy')])).rows[0];
await db.exec('reset role');
await db.exec(await readFile(migrationUrl,'utf8'));
await db.exec('set role authenticated');
ok('migration is repeatable and preserves legacy image_url', (await db.query('select image_url from ideas where id=$1',[legacy.id])).rows[0].image_url===url('legacy'));
ok('migration does not backfill/alter existing attachments', (await db.query('select count(*)::int n from idea_images')).rows[0].n===0);
for (const count of [0,1,2,5,10]) {
  const urls=Array.from({length:count},(_,i)=>url(`${count}-${i}`));
  const row=await save(db,'idea',null,values,urls);
  const images=(await db.query('select image_url,sort_order from idea_images where idea_id=$1 order by sort_order',[row.id])).rows;
  ok(`${count} images commit in selection order`,JSON.stringify(images.map(x=>x.image_url))===JSON.stringify(urls));
  ok(`${count} images keep legacy mirror compatible`,row.image_url===(urls[0]||null));
}
const added=await save(db,'idea',legacy.id,values,[url('legacy'),url('B'),url('C')],[url('legacy')],legacy.updated_at);
ok('legacy 1 + new 2 keeps original URL',added.image_url===url('legacy'));
const edited=await save(db,'idea',legacy.id,values,[url('legacy'),url('C'),url('D'),url('E')],[url('legacy'),url('B'),url('C')],added.updated_at);
ok('remove B and add D/E leaves A/C/D/E',JSON.stringify((await db.query('select image_url from idea_images where idea_id=$1 order by sort_order',[legacy.id])).rows.map(x=>x.image_url))===JSON.stringify([url('legacy'),url('C'),url('D'),url('E')]));
await assert.rejects(save(db,'idea',legacy.id,values,[],[url('legacy')],legacy.updated_at),/他の更新/);
ok('stale edits do not remove newer attachments',(await db.query('select count(*)::int n from idea_images where idea_id=$1',[legacy.id])).rows[0].n===4);
await assert.rejects(save(db,'idea',null,values,Array(11).fill(0).map((_,i)=>url(`limit-${i}`))),/最大10枚/);
await assert.rejects(save(db,'idea',null,values,[url('duplicate'),url('duplicate')]),/重複/);
await assert.rejects(save(db,'idea',null,values,['javascript:alert(1)']),/URL/);
ok('limits/duplicate/unsafe URL rejected',true);
await db.query('insert into storage.objects(bucket_id,name) values($1,$2),($1,$3)',['idea-images','ideas/legacy.png','ideas/B.png']);
ok('read existing Storage object',(await db.query('select count(*)::int n from storage.objects')).rows[0].n===2);
ok('referenced legacy Storage file cannot be deleted',(await db.query("delete from storage.objects where name='ideas/legacy.png' returning name")).rows.length===0);
ok('detached B can be deleted',(await db.query("delete from storage.objects where name='ideas/B.png' returning name")).rows.length===1);
await db.query('update ideas set deleted_at=now() where id=$1',[legacy.id]);
ok('trash keeps referenced Storage file protected',(await db.query("delete from storage.objects where name='ideas/legacy.png' returning name")).rows.length===0);
await db.query('update ideas set deleted_at=null where id=$1',[legacy.id]);
const board=await save(db,'idea',null,{...values,status:'実行済み'},[]);
const item=await save(db,'idea_item',null,{...values,parent_idea_id:board.id},[url('item-1'),url('item-2')]);
ok('nested item supports multiple attachments',(await db.query('select count(*)::int n from idea_images where idea_item_id=$1',[item.id])).rows[0].n===2);
const moved=(await db.query('select public.move_idea_to_completed_parent($1,$2) result',[legacy.id,board.id])).rows[0].result;
ok('move transfers all images before source deletion',(await db.query('select count(*)::int n from idea_images where idea_item_id=$1',[moved.item_id])).rows[0].n===4);
ok('moved image remains protected',(await db.query("delete from storage.objects where name='ideas/legacy.png' returning name")).rows.length===0);
const sharedA=await save(db,'idea',null,values,[url('shared')]);
const sharedB=await save(db,'idea_item',null,{...values,parent_idea_id:board.id},[url('shared')]);
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['idea-images','ideas/shared.png']);
await save(db,'idea',sharedA.id,values,[],[url('shared')],sharedA.updated_at);
ok('other parent reference protects a shared file',(await db.query("delete from storage.objects where name='ideas/shared.png' returning name")).rows.length===0);
await save(db,'idea_item',String(sharedB.id),values,[],[url('shared')],sharedB.updated_at);
ok('last explicit reference removal permits file cleanup',(await db.query("delete from storage.objects where name='ideas/shared.png' returning name")).rows.length===1);
const first=await save(db,'idea',null,values,[url('atomic')]);
await db.exec(`reset role; create function public.qa_reject_image() returns trigger language plpgsql as $$begin if new.image_url like '%reject%' then raise exception 'simulated image insert failure'; end if; return new; end$$; create trigger qa_reject before insert on public.idea_images for each row execute function public.qa_reject_image(); set role authenticated;`);
await assert.rejects(save(db,'idea',first.id,{...values,title:'must roll back'},[url('reject')],[url('atomic')],first.updated_at),/simulated/);
const after=(await db.query('select * from ideas where id=$1',[first.id])).rows[0];
ok('attachment failure rolls back parent fields and first image',after.title===first.title&&after.image_url===first.image_url);
ok('attachment failure rolls back detached rows',(await db.query('select image_url from idea_images where idea_id=$1',[first.id])).rows[0].image_url===url('atomic'));
await db.query("select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',false)");
ok('second authenticated user retains shared-channel read access',(await db.query('select count(*)::int n from idea_images')).rows[0].n>0);
ok('second authenticated user retains shared-channel write access',Boolean((await save(db,'idea',null,values,[url('second-user')])).id));
await db.exec('set role anon');
await assert.rejects(db.query('select * from idea_images'),/permission denied/);
await assert.rejects(save(db,'idea',null,values,[]),/permission denied/);
ok('anonymous read/write denied',true);
await db.exec("set role authenticated; select set_config('request.jwt.claim.sub','',false)");
await assert.rejects(save(db,'idea',null,values,[]),/ログイン/);
ok('RPC checks authenticated user',true);
await db.close();
console.log(`\n${checks} database/RLS/storage-policy tests passed`);
