// Read the existing SQL, execute selected definitions in local PGlite only.
// Deliberately exclude the baseline's Vault / Cron / extension installation.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createDatabase } from './fixtures/idea-images-db.mjs';
const db=await createDatabase();
const sql=await readFile(new URL('../ver23_20_supabase.sql',import.meta.url),'utf8');
let checks=0;
const ok=(name,value)=>{assert(value,name);checks++;console.log('PASS '+name);};
await db.exec(`reset role;
  create table auth.users(id uuid primary key,deleted_at timestamptz);
  insert into auth.users values('00000000-0000-4000-8000-000000000001',null),('00000000-0000-4000-8000-000000000002',null);
  create table goals(id uuid primary key default gen_random_uuid(),title text,goal_scope text,goal_month text,goal_key text,target_value integer,deleted_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
  create table videos(id uuid primary key default gen_random_uuid(),title text,video_type text,status text,post_date date,youtube_url text,tags text,memo text,youtube_views bigint,deleted_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
  create table notifications(id uuid primary key default gen_random_uuid(),title text,message text,entity_type text,entity_id text,is_read boolean,recipient_user_id uuid,actor_user_id uuid,event_key text,created_at timestamptz,unique(recipient_user_id,event_key));
  grant select,insert,update,delete on goals,videos,notifications to authenticated;
  insert into goals(title,goal_scope,goal_month,goal_key,target_value) values('saved past target','monthly','2020-01','posts',10);
`);
const snapshotStart=sql.indexOf('create table if not exists public.monthly_achievement_snapshots');
const snapshotEnd=sql.indexOf('-- Supabase公式のpg_cron');
await db.exec(sql.slice(snapshotStart,snapshotEnd));
const notificationStart=sql.indexOf('create or replace function public.create_channel_change_notifications()');
const notificationEnd=sql.indexOf('-- Realtimeへの登録');
await db.exec(sql.slice(notificationStart,notificationEnd));
const month=(await db.query('select public.current_jst_month_key() as month_key')).rows[0].month_key;
await db.exec('set role authenticated');
await db.query("insert into goals(title,goal_scope,goal_month,goal_key,target_value) values('current','monthly',$1,'posts',10)",[month]);
ok('current-month target can be saved',true);
await assert.rejects(db.query("insert into goals(title,goal_scope,goal_month,goal_key,target_value) values('past','monthly','2020-01','posts',10)"),/過去月/);
ok('past-month target insert is rejected by existing trigger',true);
await assert.rejects(db.query("update goals set target_value=99 where goal_month='2020-01'"),/過去月/);
ok('saved past-month target update is rejected',true);
await assert.rejects(db.query("delete from goals where goal_month='2020-01'"),/過去月/);
ok('saved past-month target deletion is rejected',true);
await db.exec("reset role; insert into monthly_achievement_snapshots(month_key,subscriber_count,post_count) values('2020-01',null,3); set role authenticated;");
ok('authenticated snapshot read keeps nullable subscriber count',(await db.query('select subscriber_count from monthly_achievement_snapshots')).rows[0].subscriber_count===null);
await assert.rejects(db.query("update monthly_achievement_snapshots set post_count=100"),/permission denied/);
ok('authenticated snapshot write denied',true);
await db.exec('reset role');
await assert.rejects(db.query("update monthly_achievement_snapshots set post_count=100"),/確定済み/);
await assert.rejects(db.query('delete from monthly_achievement_snapshots'),/確定済み/);
ok('even privileged snapshot update/delete rejected by immutable trigger',true);
await db.exec('set role authenticated');
const video=(await db.query("insert into videos(title,video_type,status) values('video','Shorts','投稿済み') returning id")).rows[0];
let notifications=(await db.query('select * from notifications')).rows;
ok('video creates exactly one notification for the other user',notifications.length===1&&notifications[0].recipient_user_id==='00000000-0000-4000-8000-000000000002');
await db.query('update videos set youtube_views=12500,updated_at=clock_timestamp() where id=$1',[video.id]);
ok('YouTube-only update produces no notification',(await db.query('select count(*)::int n from notifications')).rows[0].n===1);
await db.query("update videos set title='edited',updated_at=clock_timestamp() where id=$1",[video.id]);
ok('editorial video update produces a notification',(await db.query('select count(*)::int n from notifications')).rows[0].n===2);
const idea=(await db.query("insert into ideas(title,status) values('idea','実行済み') returning id")).rows[0];
await db.query("insert into idea_items(parent_idea_id,title) values($1,'nested')",[idea.id]);
ok('idea insert notifies; nested idea does not',(await db.query('select count(*)::int n from notifications')).rows[0].n===3);
await db.query('update goals set target_value=20,updated_at=clock_timestamp() where goal_month=$1',[month]);
ok('monthly target updates do not notify',(await db.query('select count(*)::int n from notifications')).rows[0].n===3);
await db.query('insert into notifications(title,recipient_user_id,event_key) select title,recipient_user_id,event_key from notifications on conflict do nothing');
ok('recipient/event_key protects against duplicates',(await db.query('select count(*)::int n from notifications')).rows[0].n===3);
await db.close();
console.log(`\n${checks} monthly/notification SQL tests passed`);
