-- Additive only. Existing image_url values and Storage files are not migrated or removed.
begin;

create table if not exists public.idea_images (
  id uuid primary key default gen_random_uuid(),
  idea_id uuid references public.ideas(id) on delete cascade,
  idea_item_id bigint references public.idea_items(id) on delete cascade,
  image_url text not null check (image_url ~* '^https?://' and length(image_url) <= 4096),
  storage_path text,
  sort_order integer not null check (sort_order >= 0),
  created_at timestamptz not null default now(),
  constraint idea_images_one_parent check (num_nonnulls(idea_id, idea_item_id) = 1),
  unique (idea_id, image_url),
  unique (idea_item_id, image_url)
);
-- The unique indexes above also index both foreign keys.
create index if not exists idea_images_storage_path_idx on public.idea_images(storage_path);
alter table public.idea_images enable row level security;
revoke all on public.idea_images from anon;
grant select, insert, update, delete on public.idea_images to authenticated;
grant all on public.idea_images to service_role;

-- Same shared-channel access as the existing ideas / idea_items policies.
do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'idea_images' and policyname = 'authenticated idea images') then
    create policy "authenticated idea images" on public.idea_images
      for all to authenticated using (true) with check (true);
  end if;
end $$;

-- Only paths generated by the app are eligible for automatic deletion.
-- Matching any host here is deliberately conservative: even a legacy reference
-- on another host protects a same-named object from deletion in this bucket.
create or replace function public.idea_image_object_path(p_url text)
returns text language sql immutable set search_path = '' as $$
  select substring(p_url from '^https?://[^/]+/storage/v1/object/public/idea-images/((?:ideas|idea-items|idea)/[A-Za-z0-9._-]+)(?:[?#].*)?$');
$$;

create or replace function public.idea_image_is_unreferenced(p_path text)
returns boolean language sql stable security invoker set search_path = '' as $$
  select p_path ~ '^(ideas|idea-items|idea)/[A-Za-z0-9._-]+$'
    and not exists (select 1 from public.idea_images i
      where i.storage_path = p_path or public.idea_image_object_path(i.image_url) = p_path)
    and not exists (select 1 from public.ideas i
      where public.idea_image_object_path(i.image_url) = p_path)
    and not exists (select 1 from public.idea_items i
      where public.idea_image_object_path(i.image_url) = p_path);
$$;
revoke all on function public.idea_image_object_path(text), public.idea_image_is_unreferenced(text) from public, anon;
grant execute on function public.idea_image_object_path(text), public.idea_image_is_unreferenced(text) to authenticated, service_role;

-- Storage API performs the physical deletion; SQL never deletes storage.objects.
-- Referenced files (including legacy images and items in the trash) stay protected.
do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'storage'
    and tablename = 'objects' and policyname = 'authenticated delete unreferenced idea images') then
    create policy "authenticated delete unreferenced idea images" on storage.objects
      for delete to authenticated using (
        bucket_id = 'idea-images' and public.idea_image_is_unreferenced(name)
      );
  end if;
end $$;

-- Parent fields, legacy first-image mirror and ordered attachments commit together.
-- The client sends additions and explicit removals, never a replacement image list.
-- Invoker rights preserve existing table RLS. The expected snapshot prevents a
-- stale editor from removing images added by another user while editing.
create or replace function public.save_idea_with_images(
  p_kind text,
  p_id text,
  p_values jsonb,
  p_added_image_urls text[],
  p_removed_image_urls text[],
  p_expected_image_urls text[],
  p_expected_updated_at timestamptz
)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_idea public.ideas%rowtype;
  v_item public.idea_items%rowtype;
  v_idea_id uuid;
  v_item_id bigint;
  v_legacy text;
  v_updated_at timestamptz;
  v_current_urls text[] := array[]::text[];
  v_image_urls text[];
  v_url text;
  v_position integer := 0;
  v_result jsonb;
begin
  if auth.uid() is null then raise exception 'ログインが必要です。' using errcode = '42501'; end if;
  if p_kind not in ('idea', 'idea_item') or p_kind is null then raise exception '画像の保存先が不正です。'; end if;
  if nullif(btrim(p_values->>'title'), '') is null then raise exception '企画名を入力してください。'; end if;
  if coalesce(p_values->>'status', '') not in ('アイデア', '実行済み') then raise exception 'ステータスが不正です。'; end if;
  if p_added_image_urls is null or p_removed_image_urls is null then raise exception '画像の追加・削除指定が不正です。'; end if;
  if exists (select 1 from unnest(p_added_image_urls) u where u is null or u !~* '^https?://' or length(u) > 4096)
    or cardinality(p_added_image_urls) <> (select count(distinct u) from unnest(p_added_image_urls) u) then
    raise exception '画像URLが不正、または重複しています。';
  end if;

  if p_id is not null then
    if p_kind = 'idea' then
      select * into v_idea from public.ideas where id = p_id::uuid and deleted_at is null for update;
      if not found then raise exception '企画が見つかりません。'; end if;
      v_idea_id := v_idea.id; v_legacy := v_idea.image_url; v_updated_at := v_idea.updated_at;
    else
      select * into v_item from public.idea_items where id = p_id::bigint for update;
      if not found then raise exception '企画内アイデアが見つかりません。'; end if;
      v_item_id := v_item.id; v_legacy := v_item.image_url; v_updated_at := v_item.updated_at;
    end if;
    select coalesce(array_agg(image_url order by sort_order, created_at, id), array[]::text[])
      into v_current_urls from public.idea_images
      where idea_id = v_idea_id or idea_item_id = v_item_id;
    if nullif(v_legacy, '') is not null and not (v_legacy = any(v_current_urls)) then
      v_current_urls := array_prepend(v_legacy, v_current_urls);
    end if;
    if v_current_urls is distinct from p_expected_image_urls
      or v_updated_at is distinct from p_expected_updated_at then
      raise exception '他の更新がありました。編集を閉じて最新の内容を確認してください。' using errcode = '40001';
    end if;
  end if;

  if exists (select 1 from unnest(p_removed_image_urls) u where u is null or not (u = any(v_current_urls))) then
    raise exception '保存済みでない画像は削除できません。';
  end if;
  if exists (select 1 from unnest(p_added_image_urls) u where u = any(v_current_urls)) then
    raise exception '保存済み画像を再追加することはできません。';
  end if;
  select coalesce(array_agg(u order by position), array[]::text[]) into v_image_urls
    from unnest(v_current_urls) with ordinality as images(u, position)
    where not (u = any(p_removed_image_urls));
  v_image_urls := v_image_urls || p_added_image_urls;
  if cardinality(v_image_urls) > 10 then raise exception '画像は最大10枚です。'; end if;

  if p_kind = 'idea' then
    if p_id is null then
      insert into public.ideas(title, status, note, tags, image_url, updated_at)
        values (btrim(p_values->>'title'), p_values->>'status', coalesce(p_values->>'note',''),
          coalesce(p_values->>'tags',''), v_image_urls[1], clock_timestamp())
        returning * into v_idea;
      v_idea_id := v_idea.id;
    else
      update public.ideas set title = btrim(p_values->>'title'), status = p_values->>'status',
        note = coalesce(p_values->>'note',''), tags = coalesce(p_values->>'tags',''),
        image_url = v_image_urls[1], updated_at = clock_timestamp()
        where id = v_idea_id returning * into v_idea;
      if not found then raise exception '企画を更新できません。' using errcode = '42501'; end if;
    end if;
    v_result := to_jsonb(v_idea);
  else
    if p_id is null then
      perform 1 from public.ideas where id::text = p_values->>'parent_idea_id'
        and status = '実行済み' and deleted_at is null for share;
      if not found then raise exception '追加先の企画ボードが見つかりません。'; end if;
      insert into public.idea_items(parent_idea_id, title, status, note, image_url, updated_at)
        values (p_values->>'parent_idea_id', btrim(p_values->>'title'), p_values->>'status',
          coalesce(p_values->>'note',''), v_image_urls[1], clock_timestamp()) returning * into v_item;
      v_item_id := v_item.id;
    else
      update public.idea_items set title = btrim(p_values->>'title'), status = p_values->>'status',
        note = coalesce(p_values->>'note',''), image_url = v_image_urls[1], updated_at = clock_timestamp()
        where id = v_item_id returning * into v_item;
      if not found then raise exception '企画内アイデアを更新できません。' using errcode = '42501'; end if;
    end if;
    v_result := to_jsonb(v_item);
  end if;

  -- A missing client file is never interpreted as a deletion.
  delete from public.idea_images where (idea_id = v_idea_id or idea_item_id = v_item_id)
    and image_url = any(p_removed_image_urls);
  foreach v_url in array v_image_urls loop
    if p_kind = 'idea' then
      insert into public.idea_images(idea_id, image_url, storage_path, sort_order)
        values (v_idea_id, v_url, public.idea_image_object_path(v_url), v_position)
        on conflict (idea_id, image_url) do update set sort_order = excluded.sort_order;
    else
      insert into public.idea_images(idea_item_id, image_url, storage_path, sort_order)
        values (v_item_id, v_url, public.idea_image_object_path(v_url), v_position)
        on conflict (idea_item_id, image_url) do update set sort_order = excluded.sort_order;
    end if;
    v_position := v_position + 1;
  end loop;
  return v_result;
end;
$$;
revoke all on function public.save_idea_with_images(text,text,jsonb,text[],text[],text[],timestamptz) from public, anon;
grant execute on function public.save_idea_with_images(text,text,jsonb,text[],text[],text[],timestamptz) to authenticated;

-- Keep the existing explicit move behavior, transferring all attachments before
-- the source record is removed. No move or deletion is executed by this migration.
create or replace function public.move_idea_to_completed_parent(
  p_source_idea_id text, p_target_idea_id text
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_source public.ideas%rowtype;
  v_target public.ideas%rowtype;
  v_new_item_id text;
begin
  if auth.uid() is null then raise exception 'ログインが必要です。'; end if;
  select * into v_source from public.ideas
    where id::text = p_source_idea_id and deleted_at is null for update;
  if not found then raise exception '移動元の企画が見つかりません。'; end if;
  if v_source.status <> 'アイデア' then raise exception 'アイデア状態の企画だけ移動できます。'; end if;
  select * into v_target from public.ideas
    where id::text = p_target_idea_id and deleted_at is null for update;
  if not found then raise exception '移動先の企画が見つかりません。'; end if;
  if v_target.status <> '実行済み' then raise exception '企画ボードだけを移動先にできます。'; end if;
  insert into public.idea_items(parent_idea_id,title,note,status,image_url,created_at,updated_at)
    values (p_target_idea_id,v_source.title,coalesce(v_source.note,''),'アイデア',v_source.image_url,now(),now())
    returning id::text into v_new_item_id;
  update public.idea_images set idea_id = null, idea_item_id = v_new_item_id::bigint
    where idea_id = v_source.id;
  delete from public.ideas where id::text = p_source_idea_id;
  return jsonb_build_object('item_id',v_new_item_id,'parent_idea_id',p_target_idea_id,'title',v_source.title);
end;
$$;
revoke all on function public.move_idea_to_completed_parent(text,text) from public, anon;
grant execute on function public.move_idea_to_completed_parent(text,text) to authenticated;

-- Existing parent UPDATE/INSERT events carry the attachment transaction through
-- the existing Realtime subscriptions; no publication or notification changes.
notify pgrst, 'reload schema';
commit;
